# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: azure-test

stages:
- stage: build
  displayName: 'Build Stage'
  jobs:
  - job: 
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Restoring project dependencies..."
      displayName: 'Restore dependencies'
    - script: 
        echo "Running Unit Tests" 
      displayName: 'Run Unit Tests'

- stage: test      
  displayName: 'Test Stage'
  dependsOn: Build
  isSkippable: false
  jobs:
  - job:
    displayName: 'Test Job'
    steps:
    - script: |
        echo "Running unit tests"
      displayName: 'Running Unit Tests'

- stage: DeployToStaging
  displayName: 'Deploy to Staging'  
  dependsOn: test
  jobs:
  - job:
    displayName: 'DeployStagingJob'
# pool: azure-test
    steps:
    - script: |
        echo "Build staging job"
      displayName: 'Build and Deploy to Staging'

  - job: DeployStagingJobWithValidation
    pool: server
    timeoutInMinutes: 2
    displayName: 'Deploy to Staging Job'      
    steps:
    - task: ManualValidation@1
      timeoutInMinutes: 1
      inputs:
        notifyUsers: 'chethanp4888@outlook.com'
        instructions: 'Please validate the stage configuration and resume'
        onTimeout: 'reject'
