# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: azure-test

stages:
- stage: build
  displayName: 'Build Stage'
  jobs:
  - job:
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Restoring project dependencies..."
      displayName: 'Restore dependencies'
    - script: 
        echo "Running Unit Tests" 
      displayName: 'Run Unit Tests'  
